#!/usr/bin/env bash

lines="-l 20"
selected="$(ps -a -u $USER | \
            dmenu -i  \
            -p "kill >" \
            $lines  | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Yes\nNo" | \
            dmenu -i -p "kill $selected?" \
            $lines $colors $font )"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
